-- CreateTable
CREATE TABLE "Patron" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "Book" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "ISBN" TEXT NOT NULL,
    "Title" TEXT NOT NULL,
    "Author" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "patronId" INTEGER NOT NULL,
    CONSTRAINT "Book_patronId_fkey" FOREIGN KEY ("patronId") REFERENCES "Patron" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
