services:
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "81:8080"
  #   volumes:
  #     - ./compose.db:/app/app.db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      - API_URI=http://backend:8080
    volumes:
      - ./compose.db:/app/app.db
